version: '3.8'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  cocktails:
    depends_on:
      db:
        condition: service_healthy
    image: milevaaleks/crafty-cocktails:v3
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - USERNAME=root
      - FORTUNES_SERVICE_HOST=fortunes
  fortunes:
    depends_on:
      cocktails:
        condition: service_started
      db:
        condition: service_healthy
    image: milevaaleks/drinking-fortunes:v2
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - USERNAME=root
