spring:
  messages:
    encoding: UTF-8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/cocktail-db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${USERNAME:root}
    password: ${PASSWORD:}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
#    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

cloudinary:
  api-key: ${CLAUDINARY_API_KEY:}
  api-secret: ${CLAUDINARY_API_SECRET:}
  cloud-name: dlknl4mzd

mail:
  host: smtp.gmail.com
  port: 587
  username: aleksandramileva96@gmail.com
  password: ${EMAIL_PASSWORD:}

site:
  base:
    url: http://localhost:8080


home:
  page:
#    Execute at 00:00, 16:00 every day
    cron: "0 0 0,16 * * ?"

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
